name: ShellCheck Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't fail the build if errors are found
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck on scripts/
        run: |
          echo "Checking shell scripts in ./scripts"
          find scripts -name "*.sh" -print -exec shellcheck {} +
